import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import StoreProvider from "./storeProvider";
import Navbar from "./components/Navbar/navbar";
import { useEffect, useState } from "react";
import { getCookie } from "../../utils/cookies";
import NavbarLogin from "./components/Navbar/navbarLogin";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "600", "700", "800"],
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie=await getCookie("login"); 
  return (
    <html lang="en">
      <body className={poppins.className}>
        <StoreProvider>
          <p>{cookie}</p>
          {/* {cookie==="not authorized"&&<Navbar></Navbar>}
          {cookie==="authorized"&&<NavbarLogin></NavbarLogin>} */}
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
